/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "FingerprintSetDLG.h"
#include "wk2xxx.h"
#include "finger.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0         (GUI_ID_USER + 0x00)
#define ID_LISTBOX_0         (GUI_ID_USER + 0x01)
#define ID_BUTTON_0         (GUI_ID_USER + 0x02)
#define ID_BUTTON_1         (GUI_ID_USER + 0x04)
#define ID_TEXT_0         (GUI_ID_USER + 0x05)


// USER START (Optionally insert additional defines)
#define REGISTER_NUM  3
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

typedef struct
{
  uint8_t id;
  int Verify;
  int Register;
  char name[20];
}Fingerprint_t;

uint8_t FingerprintMode = 0;//0--verify,1--register
short FingerprintIndex = 0;

Fingerprint_t Fingerprint = {0};

const char FingerprintText[][32] = {
  {"Fingerprint Registered"},
  {"指纹注册"},
};
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "FingerprintSet", ID_FRAMEWIN_0, 20, 40, 280, 180, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 0, 270, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Close", ID_BUTTON_0, 10, 120, 80, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Setup", ID_BUTTON_1, 180, 120, 80, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 90, 270, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  char buf[64];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'FingerprintSet'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 20);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem, FontList16[System.font]);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_SetFont(hItem, FontList16[System.font]);
    //
    // Initialization of 'Close'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    //
    // Initialization of 'Setup'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, FontList16[System.font]);
    TEXT_SetText(hItem," ");
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, Fingerprint.name);
    LISTBOX_SetSel(hItem,0);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        FingerprintIndex = LISTBOX_GetSel(hItem);
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        process_post_synch(&FingerprintProcess,AppCloseEvent,NULL);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Setup'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_CreateTimer(WM_GetClientWindow(pMsg->hWin), 0x85, 50, 0);
        process_post_synch(&FingerprintProcess,AppInputEvent,NULL);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  case WM_TIMER:
    WM_RestartTimer(pMsg->Data.v, 50);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    sprintf(buf,"%s (%d)",(char*)FingerprintText[System.language],Fingerprint.Register);
    TEXT_SetText(hItem,buf);
    break;
  case WM_PAINT:
    WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFingerprintSet
*/
WM_HWIN CreateFingerprintSet(void);
WM_HWIN CreateFingerprintSet(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)

void FingerprintProcessInit()
{
  Fingerprint.id = 1;
  sprintf(Fingerprint.name,"Fingerprint");
  
	Wk2114PortInit(3);
	Wk2114SetBaud(3,57600);
  Wk2114_SlaveRecv_Set(3,finger_usartInput);
  
  finger_init();
  finger_SetSendByteCall(Wk2114_Uart3SendByte);
}

void FingerprintProcessPoll()
{
  short temp = 0;
  
  finger_uartAnalysis();
  if(FingerprintMode == 0)
  {
    if(LockScreenGet())
    {
      if(Fingerprint.Verify)
      {
        temp = finger_getIdentifyInfo();
        if(temp == 1)
        {
          Fingerprint.Verify = 0;
          finger_cancel();
          process_post_synch(&LockScreenProcess,AppInputEvent,NULL);
        }
        else if(temp == -1)
        {
          Fingerprint.Verify = 0;
          finger_cancel();
        }
      }
      else
      {
        Fingerprint.Verify = 1;
        finger_autoIdentify(Fingerprint.id,3);
      }
    }
    else if(Fingerprint.Verify)
    {
      Fingerprint.Verify = 0;
      finger_cancel();
    }
  }
  else
  {
    temp = finger_getEnrollInfo();
    if(temp == 0)
    {
      FingerprintMode = 0;
      Fingerprint.Register = REGISTER_NUM;
    }
    else
    {
      Fingerprint.Register = temp;
    }
  }
}

PROCESS(FingerprintProcess, "FingerprintProcess");

PROCESS_THREAD(FingerprintProcess, ev, data)
{
  static struct etimer et_Fingerprint; 
  
  PROCESS_BEGIN();
  
  FingerprintProcessInit();
  process_post(&FingerprintProcess,PROCESS_EVENT_TIMER,NULL);
  
  while (1)
  {
    PROCESS_WAIT_EVENT();  
    if(ev == PROCESS_EVENT_TIMER)
    {
      etimer_set(&et_Fingerprint,100);
      FingerprintProcessPoll();
    }
    if(ev == AppInputEvent)
    {
      FingerprintMode = 1;
      Fingerprint.Register = 0;
      finger_cancel();
      finger_autoEnroll(Fingerprint.id,REGISTER_NUM);
    }
    if(ev == AppOpenEvent)
    {
      CreateFingerprintSet();
    }
    if(ev == AppCloseEvent)
    {
      if(FingerprintMode)
      {
        finger_cancel();
        FingerprintMode = 0;
      }
    }
  }
  
  PROCESS_END();
}
// USER END

/*************************** End of file ****************************/
