/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_0   (GUI_ID_USER + 0x01)
#define ID_TEXT_0   (GUI_ID_USER + 0x03)
#define ID_LISTBOX_0   (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
typedef struct
{
  short time;
  const char* text;
}LockScreenSet_t;

LockScreenSet_t LockScreenSetText[][7] = {
  {
    15,   " 15 second ",
    30,   " 30 second ",
    60,   " 1 minute ",
    120,  " 2 minute ",
    300,  " 5 minute ",
    600,  " 10 minute ",
    1800, " 30 minute ",
  },
  {
    15,   " 15秒 ",
    30,   " 30秒 ",
    60,   " 1分钟 ",
    120,  " 2分钟 ",
    300,  " 5分钟 ",
    600,  " 10分钟 ",
    1800, " 30分钟 ",
  },
};



#define ITEM_SIZEX  290
#define ITEM_SIZEY  30

static int _OwnerDraw(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo) {
  unsigned char colorIndex = 0;
  char strBuf[100] = {0};
  int FontDistY = 0;
  GUI_COLOR aColor[2] = {GUI_BLACK, GUI_WHITE};
  GUI_COLOR bkColor[2] = {GUI_WHITE, GUI_BLUE};
  switch (pDrawItemInfo->Cmd) {
  case WIDGET_ITEM_GET_XSIZE:
    return ITEM_SIZEX;
    break;
  case WIDGET_ITEM_GET_YSIZE:
    return ITEM_SIZEY;
    break;
  case WIDGET_ITEM_DRAW:
    if(LISTBOX_GetSel(pDrawItemInfo->hWin) == pDrawItemInfo->ItemIndex)
      colorIndex = 1;
    else
      colorIndex = 0;
    GUI_SetBkColor(bkColor[colorIndex]);
    GUI_Clear();
    LISTBOX_GetItemText(pDrawItemInfo->hWin, pDrawItemInfo->ItemIndex, strBuf, sizeof(strBuf));
    FontDistY  = GUI_GetFontDistY();
    GUI_SetColor(aColor[colorIndex]);
    GUI_DispStringAt(strBuf, pDrawItemInfo->x0 + 0, pDrawItemInfo->y0 + (ITEM_SIZEY - FontDistY) / 2);
    GUI_SetColor(GUI_GRAY);
    if(LISTBOX_GetNumItems(pDrawItemInfo->hWin)-1 != pDrawItemInfo->ItemIndex)
      GUI_DrawHLine(pDrawItemInfo->y0 + ITEM_SIZEY - 1, pDrawItemInfo->x0 + 10, ITEM_SIZEX - 10);
    GUI_DispStringAt(">", pDrawItemInfo->x0 + ITEM_SIZEX - 2 * 10, pDrawItemInfo->y0 + (ITEM_SIZEY - FontDistY) / 2);
    break;
  default:
    LISTBOX_OwnerDraw(pDrawItemInfo);
    break;
  }
  return 0;
}
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "LockScreenSet", ID_WINDOW_0, 0, 0, 320, 220, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "<<", ID_BUTTON_0, 0, 0, 40, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "title", ID_TEXT_0, 40, 0, 240, 25, 0, 0x64, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 25, 320, 195, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  short index = 0;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'LockScreenSet'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00E9E9E9));
    //
    // Initialization of '<<'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "<<");
    //
    // Initialization of 'title'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, FontList16[System.font]);
    TEXT_SetText(hItem, "LockScreenSet");
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_SetFont(hItem, FontList16[System.font]);
    LISTBOX_SetTextAlign(hItem,GUI_TA_VCENTER);
    LISTBOX_SetAutoScrollV(hItem,1);
    LISTBOX_SetScrollbarWidth(hItem,20);
    LISTBOX_SetItemSpacing(hItem,14);
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    for(short i=0;i<GUI_COUNTOF(LockScreenSetText[System.language]);i++)
    {
      LISTBOX_AddString(hItem, LockScreenSetText[System.language][i].text);
    }
    switch(LockScreenTimeGet())
    {
    case 15://LockScreenSetText[System.language][0].time:
      LISTBOX_SetSel(hItem,0);
      break;
    case 30:
      LISTBOX_SetSel(hItem,1);
      break;
    case 60:
      LISTBOX_SetSel(hItem,2);
      break;
    case 120:
      LISTBOX_SetSel(hItem,3);
      break;
    case 300:
      LISTBOX_SetSel(hItem,4);
      break;
    case 600:
      LISTBOX_SetSel(hItem,5);
      break;
    case 1800:
      LISTBOX_SetSel(hItem,6);
      break;
    default:
      LISTBOX_SetSel(hItem,-1);
    }
    LISTBOX_SetOwnerDraw(hItem, _OwnerDraw);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '<<'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        index = LISTBOX_GetSel(hItem);
        LockScreenTimeSet(LockScreenSetText[System.language][index].time);
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateLockScreenSet
*/
WM_HWIN CreateLockScreenSet(void);
WM_HWIN CreateLockScreenSet(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWinSetting, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
