/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x15)
#define ID_TEXT_0   (GUI_ID_USER + 0x16)
#define ID_BUTTON_0   (GUI_ID_USER + 0x18)
#define ID_BUTTON_1   (GUI_ID_USER + 0x19)
#define ID_LISTBOX_0   (GUI_ID_USER + 0x1A)


// USER START (Optionally insert additional defines)
extern WM_HWIN hWinCalendar;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
typedef struct
{
  char minute;
  char secend;
  short millisecond_100;
}CountTimer_t;

char CountEnable=0;
static CountTimer_t Time={0};

const char CountTimeText[][4][8]={
  {
    {"Start"},
    {"Reset"},
    {"Stop"},
    {"Count"},
  },
  {
    {"启动"},
    {"复位"},
    {"停止"},
    {"计数"},
  },
};
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "CountTime", ID_WINDOW_0, 0, 0, 320, 200, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "time", ID_TEXT_0, 40, 5, 240, 50, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "start", ID_BUTTON_0, 20, 160, 100, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "count", ID_BUTTON_1, 200, 160, 100, 30, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 20, 70, 280, 80, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void CountTime()
{
  Time.millisecond_100++;
  if(Time.millisecond_100>9)
  {
    Time.millisecond_100=0;
    Time.secend++;
    if(Time.secend>59)
    {
      Time.secend=0;
      Time.minute++;
      if(Time.minute>99)
      {
        Time.minute=0;
      }
    }
  }
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  char buf[32];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_D48);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "00:00:0");
    //
    // Initialization of 'start'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, FontList24[System.font]);
    BUTTON_SetText(hItem, CountTimeText[System.language][0]);
    //
    // Initialization of 'count'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, FontList24[System.font]);
    BUTTON_SetText(hItem, CountTimeText[System.language][1]);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_SetFont(hItem, FontList16[System.font]);
    LISTBOX_SetAutoScrollV(hItem,1);
    LISTBOX_SetScrollbarWidth(hItem,15);
    LISTBOX_SetSel(hItem,-1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'start'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        CountEnable=!CountEnable;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'count'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        if(CountEnable)
        {
          short num=LISTBOX_GetNumItems(hItem);
          if(num<50)
          {
            sprintf(buf,"%02u:    %02u:%02u:%1u",num+1,Time.minute,Time.secend,Time.millisecond_100);
            LISTBOX_AddString(hItem, buf);
          }
        }
        else
        {
          for(short i=LISTBOX_GetNumItems(hItem);i>=0;i--)
          {
            LISTBOX_DeleteItem(hItem,i);
          }
          WM_InvalidateWindow(hItem);
          Time.millisecond_100=0;
          Time.secend=0;
          Time.minute=0;
        }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  case WM_PAINT:
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    WM_SetFocus(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_SetSel(hItem,-1);
    break;
  case WM_TIMER://定时器消息,到时间时有效
    WM_RestartTimer(pMsg->Data.v, 100);
    if(CountEnable)
    {
      CountTime();
    }
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    sprintf(buf,"%02u:%02u:%1u",Time.minute,Time.secend,Time.millisecond_100);
    TEXT_SetText(hItem, buf);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    if(CountEnable)
      BUTTON_SetText(hItem, CountTimeText[System.language][2]);
    else
      BUTTON_SetText(hItem, CountTimeText[System.language][0]);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    if(CountEnable)
      BUTTON_SetText(hItem, CountTimeText[System.language][3]);
    else
      BUTTON_SetText(hItem, CountTimeText[System.language][1]);
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateCountTime
*/
WM_HWIN CreateCountTime(void);
WM_HWIN CreateCountTime(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  WM_CreateTimer(hWin, 0x81, 100, 0); //创建一个软件定时器
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
