/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_TEXT_0   (GUI_ID_USER + 0x01)
#define ID_LISTWHEEL_0   (GUI_ID_USER + 0x02)
#define ID_LISTWHEEL_1   (GUI_ID_USER + 0x03)
#define ID_LISTWHEEL_2   (GUI_ID_USER + 0x04)
#define ID_BUTTON_0   (GUI_ID_USER + 0x05)
#define ID_BUTTON_1   (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "DateSet", ID_FRAMEWIN_0, 10, 10, 300, 200, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "date", ID_TEXT_0, 0, 5, 290, 30, 0, 0x64, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel year", ID_LISTWHEEL_0, 5, 50, 90, 60, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel  month", ID_LISTWHEEL_1, 100, 50, 90, 60, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel day", ID_LISTWHEEL_2, 195, 50, 90, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "close", ID_BUTTON_0, 15, 130, 80, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "save", ID_BUTTON_1, 195, 130, 80, 35, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  short i;
  Calendar_t calendar;
  char buf[32];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'DateSet'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetClientColor(hItem,GUI_LIGHTGRAY);
    FRAMEWIN_SetTitleHeight(hItem, 20);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem, FontList16[System.font]);
    //
    // Initialization of 'date'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, 0x00808000);
    TEXT_SetFont(hItem, FontList24[System.font]);
    TEXT_SetText(hItem, "0000/00/00 week");
    //
    // Initialization of 'Listwheel year'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
    LISTWHEEL_SetTextAlign(hItem,GUI_TA_HCENTER);
    LISTWHEEL_SetTextColor(hItem,LISTWHEEL_CI_SEL,GUI_GREEN);
    LISTWHEEL_SetFont(hItem,FontList20[System.font]);
    LISTWHEEL_SetSnapPosition(hItem,20);
    //
    // Initialization of 'Listwheel  month'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
    LISTWHEEL_SetTextAlign(hItem,GUI_TA_HCENTER);
    LISTWHEEL_SetTextColor(hItem,LISTWHEEL_CI_SEL,GUI_GREEN);
    LISTWHEEL_SetFont(hItem,FontList20[System.font]);
    LISTWHEEL_SetSnapPosition(hItem,20);
    //
    // Initialization of 'Listwheel day'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
    LISTWHEEL_SetTextAlign(hItem,GUI_TA_HCENTER);
    LISTWHEEL_SetTextColor(hItem,LISTWHEEL_CI_SEL,GUI_GREEN);
    LISTWHEEL_SetFont(hItem,FontList20[System.font]);
    LISTWHEEL_SetSnapPosition(hItem,20);
    //
    // Initialization of 'close'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "Close");
    //
    // Initialization of 'save'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "Save");
    // USER START (Optionally insert additional code for further widget initialization)
    calendar=Calendar_Get();
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
    for(i=0;i<0xff;i++)
    {
      sprintf(buf,"%04u",i+2000);
      LISTWHEEL_AddString(hItem, buf);
    }
    LISTWHEEL_SetSel(hItem,calendar.year-2000);
    LISTWHEEL_MoveToPos(hItem,calendar.year-2000);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
    for(i=1;i<=12;i++)
    {
      sprintf(buf,"%02u",i);
      LISTWHEEL_AddString(hItem, buf);
    }
    LISTWHEEL_SetSel(hItem,calendar.month-1);
    LISTWHEEL_MoveToPos(hItem,calendar.month-1);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
    for(i=1;i<=31;i++)
    {
      sprintf(buf,"%02u",i);
      LISTWHEEL_AddString(hItem, buf);
    }
    LISTWHEEL_SetSel(hItem,calendar.day-1);
    LISTWHEEL_MoveToPos(hItem,calendar.day-1);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTWHEEL_0: // Notifications sent by 'Listwheel year'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
        LISTWHEEL_SetSel(hItem,LISTWHEEL_GetPos(hItem));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_1: // Notifications sent by 'Listwheel  month'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
        LISTWHEEL_SetSel(hItem,LISTWHEEL_GetPos(hItem));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_2: // Notifications sent by 'Listwheel day'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
        LISTWHEEL_SetSel(hItem,LISTWHEEL_GetPos(hItem));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        calendar = Calendar_Get();
        calendar.year = LISTWHEEL_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0))+2000;
        calendar.month = LISTWHEEL_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1))+1;
        calendar.day = LISTWHEEL_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2))+1;
        calendar.week = CountWeek(calendar.year,calendar.month,calendar.day);
        Calendar_Set(calendar);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  case WM_TIMER:
    WM_RestartTimer(pMsg->Data.v,50);
    calendar=Calendar_Get();
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    sprintf(buf,"%04u/%02u/%02u %s",calendar.year,calendar.month,calendar.day,WeekText[System.language][calendar.week]);
    TEXT_SetText(hItem, buf);
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateDateSet
*/
WM_HWIN CreateDateSetDLG(void);
WM_HWIN CreateDateSetDLG(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWinSetting, 0, 0);
  WM_CreateTimer(WM_GetClientWindow(hWin),0x81,50,0);
  FRAMEWIN_SetMoveable(hWin,1);
  WM_SetStayOnTop(hWin, 1);
  //WM_MakeModal(hWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
