/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "MotorSettingDLG.h"
#include "fml_stepmotor/fml_stepmotor.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_0   (GUI_ID_USER + 0x01)
#define ID_BUTTON_1   (GUI_ID_USER + 0x02)
#define ID_BUTTON_2   (GUI_ID_USER + 0x03)
#define ID_BUTTON_3   (GUI_ID_USER + 0x04)
#define ID_BUTTON_4   (GUI_ID_USER + 0x05)
#define ID_BUTTON_5   (GUI_ID_USER + 0x06)
#define ID_TEXT_0   (GUI_ID_USER + 0x07)
#define ID_TEXT_1   (GUI_ID_USER + 0x08)
#define ID_TEXT_2   (GUI_ID_USER + 0x09)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static uint8_t MotorSetStatus = 0;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "MotorSetting", ID_FRAMEWIN_0, 20, 40, 280, 185, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "up1", ID_BUTTON_0, 5, 30, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "down1", ID_BUTTON_1, 5, 90, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "up2", ID_BUTTON_2, 95, 30, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "down2", ID_BUTTON_3, 95, 90, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "up3", ID_BUTTON_4, 185, 30, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "down3", ID_BUTTON_5, 185, 90, 80, 60, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "1#", ID_TEXT_0, 5, 5, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "2#", ID_TEXT_1, 95, 5, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "3#", ID_TEXT_2, 185, 5, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'MotorSetting'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 25);
    FRAMEWIN_SetFont(hItem, FontList16[System.font]);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetText(hItem, "MotorSetting");
    FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,5);
    //
    // Initialization of 'up1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "UP");
    //
    // Initialization of 'down1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "DOWN");
    //
    // Initialization of 'up2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "UP");
    //
    // Initialization of 'down2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "DOWN");
    //
    // Initialization of 'up3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "UP");
    //
    // Initialization of 'down3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "DOWN");
    //
    // Initialization of '1#'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, FontList16[System.font]);
    TEXT_SetTextColor(hItem, 0x00808000);
    //
    // Initialization of '2#'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, FontList16[System.font]);
    TEXT_SetTextColor(hItem, 0x00808000);
    //
    // Initialization of '3#'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, FontList16[System.font]);
    TEXT_SetTextColor(hItem, 0x00808000);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_DELETE:
      process_post_synch(&MotorSteupProcess, AppCloseEvent, NULL);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'up1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'down1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=2;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'up2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=3;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'down2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=4;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'up3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=5;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'down3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=6;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        MotorSetStatus=0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  case WM_TIMER:
    WM_RestartTimer(pMsg->Data.v,200);
    if(MotorSetStatus != 0)
      process_post_synch(&MotorSteupProcess, AppInputEvent, &MotorSetStatus);
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMotorSetting
*/
WM_HWIN CreateMotorSetting(void);
WM_HWIN CreateMotorSetting(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  WM_CreateTimer(WM_GetClientWindow(hWin),3,200,0);
  FRAMEWIN_SetMoveable(hWin,1);
  WM_SetStayOnTop(hWin, 1);
  WM_MakeModal(hWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
void MotorSteupProcessInit()
{
  MotorSetStatus = 0;
  CreateMotorSetting();
}


PROCESS(MotorSteupProcess, "MotorSteupProcess");

PROCESS_THREAD(MotorSteupProcess, ev, data)
{
  //static struct etimer et_MotorSteup; 
  
  PROCESS_BEGIN();
  
  MotorSteupProcessInit();
  process_post(&MotorSteupProcess,PROCESS_EVENT_TIMER,NULL);
  
  while (1)
  {
    PROCESS_WAIT_EVENT();  
    if(ev == PROCESS_EVENT_TIMER)
    {
      //etimer_set(&et_MotorSteup,100);
    }
    if(ev==AppInputEvent)
    {
      switch(*((uint8_t*)data))
      {
      case 1:Stepmotor_Run(1,1,200);
        break;
      case 2:Stepmotor_Run(1,0,200);
        break;
      case 3:Stepmotor_Run(2,1,200);
        break;
      case 4:Stepmotor_Run(2,0,200);
        break;
      case 5:Stepmotor_Run(3,1,200);
        break;
      case 6:Stepmotor_Run(3,0,200);
        break;
      }
    }
    if(ev==AppCloseEvent)
    {
      PROCESS_EXIT();
    }
  }
  
  PROCESS_END();
}
// USER END

/*************************** End of file ****************************/
