/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_0   (GUI_ID_USER + 0x01)
#define ID_BUTTON_1   (GUI_ID_USER + 0x02)
#define ID_TEXT_0   (GUI_ID_USER + 0x03)
#define ID_LISTWHEEL_0   (GUI_ID_USER + 0x05)
#define ID_LISTWHEEL_1   (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "TimeSet", ID_FRAMEWIN_0, 10, 10, 300, 200, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "close", ID_BUTTON_0, 15, 130, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Save", ID_BUTTON_1, 195, 130, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "time", ID_TEXT_0, 65, 5, 160, 30, 0, 0x64, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel-hour", ID_LISTWHEEL_0, 10, 40, 130, 80, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel-minute", ID_LISTWHEEL_1, 150, 40, 130, 80, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  short i;
  Calendar_t calendar;
  char buf[128];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'TimeSet'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 20);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem, FontList16[System.font]);
    FRAMEWIN_SetClientColor(hItem,GUI_LIGHTGRAY);
    FRAMEWIN_SetText(hItem, "TimeSet");
    //
    // Initialization of 'close'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "Close");
    //
    // Initialization of 'Save'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, FontList16[System.font]);
    BUTTON_SetText(hItem, "Save");
    //
    // Initialization of 'time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, FontList24[System.font]);
    TEXT_SetTextColor(hItem, 0x00808000);
    TEXT_SetText(hItem, "00:00:00");
    //
    // Initialization of 'Listwheel-hour'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
    LISTWHEEL_SetTextAlign(hItem,GUI_TA_HCENTER);
    LISTWHEEL_SetTextColor(hItem,LISTWHEEL_CI_SEL,GUI_GREEN);
    LISTWHEEL_SetFont(hItem,FontList16[System.font]);
    LISTWHEEL_SetSnapPosition(hItem,30);
    LISTWHEEL_SetLineHeight(hItem,30);
    //
    // Initialization of 'Listwheel-minute'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
    LISTWHEEL_SetTextAlign(hItem,GUI_TA_HCENTER);
    LISTWHEEL_SetTextColor(hItem,LISTWHEEL_CI_SEL,GUI_GREEN);
    LISTWHEEL_SetFont(hItem,FontList16[System.font]);
    LISTWHEEL_SetSnapPosition(hItem,30);
    LISTWHEEL_SetLineHeight(hItem,30);
    // USER START (Optionally insert additional code for further widget initialization)
    calendar=Calendar_Get();
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
    for(i=0;i<24;i++)
    {
      sprintf(buf,"%02u",i);
      LISTWHEEL_AddString(hItem, buf);
    }
    LISTWHEEL_SetSel(hItem,calendar.hour);
    LISTWHEEL_MoveToPos(hItem,calendar.hour);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
    for(i=0;i<60;i++)
    {
      sprintf(buf,"%02u",i);
      LISTWHEEL_AddString(hItem, buf);
    }
    LISTWHEEL_SetSel(hItem,calendar.minute);
    LISTWHEEL_MoveToPos(hItem,calendar.minute);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        calendar = Calendar_Get();
        calendar.hour = LISTWHEEL_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0));
        calendar.minute = LISTWHEEL_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1));
        calendar.second = 0;
        Calendar_Set(calendar);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_0: // Notifications sent by 'Listwheel-hour'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
        LISTWHEEL_SetSel(hItem,LISTWHEEL_GetPos(hItem));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_1: // Notifications sent by 'Listwheel-minute'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
        LISTWHEEL_SetSel(hItem,LISTWHEEL_GetPos(hItem));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  case WM_TIMER:
    WM_RestartTimer(pMsg->Data.v,50);
    calendar=Calendar_Get();
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    sprintf(buf,"%02u:%02u:%02u",calendar.hour,calendar.minute,calendar.second);
    TEXT_SetText(hItem, buf);
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateTimeSet
*/
WM_HWIN CreateTimeSetDLG(void);
WM_HWIN CreateTimeSetDLG(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWinSetting, 0, 0);
  WM_CreateTimer(WM_GetClientWindow(hWin),0x80,50,0);
  FRAMEWIN_SetMoveable(hWin,1);
  WM_SetStayOnTop(hWin, 1);
  //WM_MakeModal(hWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
